name: kepler-worker

services:
  mediamtx:
    image: bluenviron/mediamtx:1
    container_name: worker-mediamtx
    volumes:
      - ./configs/mediamtx.yml:/mediamtx.yml:ro
      - ./data/dev/mediamtx/recordings:/recordings
      - ./data/dev/logs/mediamtx:/logs
    ports:
      - "9997:9997"
      - "9998:9998"
      - "8554:8554"
      - "8888:8888"
      - "8889:8889"
      - "8200:8200"
      - "8201:8201"
    networks:
      - worker
    restart: unless-stopped
    healthcheck:
      test: ['CMD', '/mediamtx', '--version']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  kepler-videos:
    driver: local

networks:
  worker:
    name: kepler_worker_network
    driver: bridge
