services:
  kepler-worker:
    # image: skylarklabs/kepler-worker-go:${VERSION:-1.0.0}
    container_name: kepler-worker-go
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - VERSION=${VERSION:-1.0.0}
    environment:
      - MAX_FPS_NO_AI=30
      - MAX_FPS_WITH_AI=30
      - PUBLISHING_FPS=30
      - NATS_URL=nats://172.17.0.1:4222
      - AI_GRPC_URL=49.248.155.76:50052
      - MEDIAMTX_URL=http://192.168.29.190:8889
      - SHOW_METADATA=true
      - SHOW_CAMERA_ID=false
      - SHOW_FRAME_ID=false
      - SHOW_RESOLUTION=false
      - SHOW_FPS=true
      - SHOW_LATENCY=false
      - SHOW_AI_STATUS=true
      - SHOW_AI_DETECTIONS_COUNT=false
      - SHOW_AI_PROCESSING_TIME=false
      - SHOW_PROJECT_COUNTS=false
      - SHOW_TIME=false
      - SHOW_QUALITY=false
      - SHOW_BITRATE=false
      - OVERLAY_COLOR="#FFFFFF"
      - OVERLAY_FONT=2
    ports:
      - "8000:8000"    # Main API
      - "8080:8080"    # Logdy web interface (if enabled)
    volumes:
      - kepler-videos:/app/kepler-videos
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  
  kepler-mediamtx:
    image: bluenviron/mediamtx:latest-ffmpeg
    container_name: kepler-mediamtx
    volumes:
      - ./configs/mediamtx.yml:/mediamtx.yml:ro
      - ./data/mediamtx/recordings:/recordings
      - ./logs/mediamtx:/logs
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: ['CMD', '/mediamtx', '--version']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    logging: *default-logging


volumes:
  kepler-videos:
    driver: local
  kepler-logs:
    driver: local
